<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Book Your Appointment - Ratnaafin Capital</title>
  <link rel="icon" href="favicon.ico" type="image/x-icon">
  <meta name="description" content="Book your appointment for video KYC with Ratnaafin Capital. Complete the process effortlessly.">
  <style>
    body, html {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background: linear-gradient(to right, #004e92, #000428);
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      color: white;
      text-align: center;
      overflow: hidden;
    }

    .booking-page {
      background: rgba(0, 0, 0, 0.8);
      padding: 30px;
      border-radius: 12px;
      width: 90%;
      max-width: 600px;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);
      animation: slideDown 1s ease-in-out;
    }

    @keyframes slideDown {
      from {
        transform: translateY(-50px);
        opacity: 0;
      }
      to {
        transform: translateY(0);
        opacity: 1;
      }
    }

    h1 {
      font-size: 1.8rem;
      margin-bottom: 20px;
    }

    p {
      font-size: 1rem;
      margin-bottom: 30px;
    }

    .book-button {
      display: inline-block;
      padding: 15px 40px;
      background: #ff5722;
      color: white;
      text-decoration: none;
      font-size: 1rem;
      font-weight: bold;
      border-radius: 8px;
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
      transition: all 0.3s ease;
    }

    .book-button:hover {
      background: #e64a19;
      box-shadow: 0 8px 20px rgba(0, 0, 0, 0.5);
      transform: scale(1.05);
    }

    .book-button:active {
      transform: scale(0.95);
    }
  </style>
</head>
<body>
  <div class="booking-page">
  <img src="https://drive.google.com/file/d/1mGkaAKtRR7-9HyGtcmOoUHBWGpXExQIQ/view?usp=sharing"/>
    <h1>Book Your Appointment</h1>
    <p>Click the button below to complete your video KYC verification with Ratnaafin Capital Private Limited.</p>
    <a 
      href="https://calendar.google.com/calendar/appointments/schedules/AcZssZ3uZzSulZPd2ibIGPnYqUZ9mqlu1hM9aUIqjl5iJuV-xNZRbdXBQLPfX3MUWGEdFjNHkbhTSeI3?gv=true" 
      class="book-button"
      target="_blank"
      rel="noopener noreferrer"
    >
      Book Now
    </a>
  </div>
</body>
</html>
